### PR TITLE
Flexible/Metered Billing API support

### PR DESCRIPTION
**Pull request by alexander-stripe**
Implement support for flexible billing options on plans and creating usage records.

### CODE REVIEW

**Comment by brandur-stripe** [comment]
Excellent, thanks.

LGTM.

**Comment by brandur-stripe** [comment]
Released as 5.8.0.

**Comment by thinkocapo** [comment]
Ok so I upgraded to `v5.8.0` so I now have access to `stripe.usageRecords`, thank you as v5.6.1 didn't have it.

Is anyone finding the `stripe.usageRecords.create` call never triggers the callback?

I can see in my Dashboard that the usage record is getting created, which is great, but I'm not getting response. Seems its hanging on the stripe end? I'm calling this stripe method the same why that i'm calling other things like `stripe.subscriptions.create` and `stripe.customers.create`, and handling the callback the same, per the api documentation.

**Comment by remi-stripe** [comment]
@thinkocapo Can you open an issue instead of commenting on the original PR? I can then follow up (I seem to be able to reproduce)

**Comment by thinkocapo** [comment]
good idea, I did https://github.com/stripe/stripe-node/issues/451 thanks

**Pull request merged**
