### PR TITLE
Expose ._res property on resources. Fixes issue #222

### PR DESCRIPTION
**Pull request by olalonde**

### CODE REVIEW

**Comment by brandur** [comment]
Nice! Thanks for the patch!

What do you think about calling it something like `lastResponse` to match the naming in the similar PHP functionality (see stripe/stripe-php#206)?

**Comment by olalonde** [comment]
Yes, sure. `lastResponse` or `_lastResponse`?

**Comment by brandur** [comment]
@olalonde I believe that the leading underscore here is a convention being used in place of JavaScript's missing visibility modifiers. Because we're intending to use `lastResponse` from outside of `StripeResource` objects, I'd vote to have no leading underscore.

**Comment by olalonde** [comment]
Ok, done :+1:

**Comment by brandur** [comment]
Great! And thanks a lot for adding the test as well.

**Comment by brandur** [comment]
Released as 4.2.0.

**Comment by olalonde** [comment]
Thanks!

**Pull request merged**
