### PR TITLE
Add explainer CHANGELOG

### PR DESCRIPTION
**Pull request by SlexAxton**
r? @brandur

### CODE REVIEW

**Comment by brandur** [comment]
LGTM!

**Comment by romainhuet** [comment]
@SlexAxton The correct link for CHANGELOG.md is https://github.com/stripe/stripe-node/blob/master/CHANGELOG.md. Thanks!

**Comment by SlexAxton** [comment]
yep.

**Comment by romainhuet** [comment]
LGTM!

**Pull request merged**
