### PR TITLE
API Updates for beta branch

### PR DESCRIPTION
**Pull request by pakrym-stripe**
Codegen for openapi v219.
cc @stripe/api-libraries

## Changelog
* Updated stable APIs to the latest version
* Add support for `Tax.Settings` resource.

### CODE REVIEW

**Review by anniel-stripe — APPROVED** [review]

**Comment by lukeed** [comment]
Hey, out of curiosity, how & where are you generating the OpenAPI -> TS definitions?

**Comment by pakrym-stripe** [comment]
@lukeed we have a generator that's currently closed-source that does that.

**Comment by lukeed** [comment]
Are there any plans to open source it? Or can you mention what OSS tool it's based on, if any? The output seems pretty great and could be very reusable

**Comment by pakrym-stripe** [comment]
We'd love to open source it but there are some organizational and technical issues to overcome so I can't promise any timelines.
The code generator is completely is not based on any open source project.

**Comment by lukeed** [comment]
Looking forward to it! But may throw something together of my own in the meantime. Thanks for the info :)

**Pull request merged**
