### PR TITLE
Add linter. Fix failures. Require linting to pass tests.

### LINKED ISSUE #209: Add Linter
Two recommendations-
* [ESLint](http://eslint.org/) w/ rules that match the current code style as closely as possible so the diff is small
* Something like [Standard](https://github.com/feross/standard), which gives you a suggested code style / rules to follow (ironically, they're not very "standard").

Usually, if organizations I've worked with have an in-house style guide or are pretty consistent throughout projects, I've seen them like ESLint more... but I'd love to PR either :)

### PR DESCRIPTION
**Pull request by SlexAxton**
Fixes #209 

Important files are pretty much just:

`.jscsrc`
`package.json`

r? @kyleconroy 
cc @mduvall @michelle

### CODE REVIEW

**Comment by SlexAxton** [comment]
Also cc @tejasmanohar

**Comment by tejasmanohar** [comment]
LGTM

**Comment by kyleconroy** [comment]
:+1:

(I hope you didn't do this all by hand)

**Comment by mduvall** [comment]
:+1: fastest typist ever, :100: WPM

**Comment by tejasmanohar** [comment]
#regex

**Comment by SlexAxton** [comment]
`jscs . --fix`

Only like 60 rules by hand (not everything can be autofixed)

**Comment by tejasmanohar** [comment]
Oh nice, just like standard's linter

**Pull request merged**
