### PR TITLE
Rename CHANGELOG to CHANGELOG.md

### PR DESCRIPTION
**Pull request by camerondubas**
Update CHANGELOG to be a Markdown file so that it displays properly in Github

### CODE REVIEW

**Comment by mujz** [comment]
+1

**Comment by SlexAxton** [comment]
Thanks!

**Comment by brandur** [comment]
@camerondubas @SlexAxton Hey guys! The only problem with this change is that it breaks a bunch of our [historical changelog links in the Stripe API Announce mailing list](https://groups.google.com/a/lists.stripe.com/forum/#!forum/api-announce). I wonder if we should at least place a backward compatible file called `CHNAGELOG` in the root directory that explains the move and links to the Markdown version?

**Comment by SlexAxton** [comment]
Good catch @brandur - I'll add one

**Comment by brandur** [comment]
> Good catch @brandur - I'll add one

Sweet. Thanks!

**Comment by SlexAxton** [comment]
https://github.com/stripe/stripe-node/pull/252

**Pull request merged**
