### PR TITLE
[WIP] Rename more parameters to match OpenAPI

### PR DESCRIPTION
**Pull request by irace-stripe**

### CODE REVIEW

**Comment by rattrayalex-stripe** [comment]
test failure looks probably real

also FYI I will be removing `urlParams: []` entirely in a shortly forthcoming PR (I assume this doesn't affect you much since it's all codegen anyway)

**Comment by irace-stripe** [comment]
@rattrayalex-stripe Yeah, I need to fix the tests, hence WIP. I shouldn’t have tagged you on this yet, that’s my mistake.

**Comment by rattrayalex-stripe** [comment]
https://github.com/stripe/stripe-node/pull/625 removes `urlParams`

**Comment by irace-stripe** [comment]
@rattrayalex-stripe I still have one failing spec I can’t seem to figure out, in case you possibly have some insight 🙏

**Comment by irace-stripe** [comment]
r?: @rattrayalex-stripe

**Comment by rattrayalex-stripe** [comment]
Looks like we need to remove `urlParams` and possibly some other things to match upstream; I'll take from here in any case! Thanks bryan!!

**Comment by irace-stripe** [comment]
@rattrayalex-stripe Is this still a valid PR or was it obviated by something else you did?

**Comment by rattrayalex-stripe** [comment]
Oops, good catch – thanks! This has been incorporated via other PR's ✅

**Pull request closed without merging**
