### PR TITLE
Add new fields to lastResponse: apiVersion, stripeAccount, idempotencyKey

### PR DESCRIPTION
**Pull request by polybuildr**
r? @jlomas-stripe  
cc @stripe/api-libraries @brandur-stripe 

If any of these three fields are set in the headers, copy them over to lastResponse as suggested in #406.
Also add tests for the new fields and refactor an existing test for lastResponse.

### CODE REVIEW

**Comment by polybuildr** [comment]
Hi @richardm-stripe! I'm glad you brought that up! I started with hardcoding the key but then came across a problem. The test isn't hermetic and actually communicates with the Stripe API, so if I hardcode an idempotency key, running the test twice gives me an error saying: `No such customer: cus_HdkOjCApDMTkzx`.

I'm not sure why it's that error specifically -- I didn't investigate. I can look into it later if you don't already know off the top of your head.

**Comment by richardm-stripe** [comment]
Ah thanks @polybuildr, I forgot about that. Can we roll our own random identifier instead of introducing a dependency?
`(Math.random() * Number.MAX_SAFE_INTEGER).toString(16)` or something?

**Comment by polybuildr** [comment]
Ah yes, that's a reasonably good solution. I'll update to include a random identifier without using a dependency. :)

**Comment by polybuildr** [comment]
Done! I know it doesn't matter, but I was still uncomfortable using `Math.random` so I used the Node crypto module's [randomBytes](https://nodejs.org/api/crypto.html#crypto_crypto_randombytes_size_callback). No additional dependencies, so that should still be okay. :)

**Comment by richardm-stripe** [comment]
Released in 8.74.0

**Comment by polybuildr** [comment]
Thanks for the review! Glad to be of help. :)

**Pull request merged**
