### PR TITLE
Add type information here and there

### PR DESCRIPTION
**Pull request by pakrym-stripe**
To simplify development and refactoring. Typechecks in `strict` mode. I've added `@ts-ignore` that require runtime changes to fix.

Types are a bit messy because the code wasn't always internally consistent but it's a start.

No runtime changes. No public type changes.

### CODE REVIEW

**Review by anniel-stripe — APPROVED** [review]
Thank you for adding these!!

**Comment by pakrym-stripe** [comment]
I'll merge after major.

**Comment by pakrym-stripe** [comment]
@anniel-stripe this needs a re-review.

**Review by anniel-stripe — APPROVED** [review]

**Comment by pakrym-stripe** [comment]
I won't wait for major. I'll merge master into `sdk-release/next-major` after merging this.

**Pull request merged**
