### PR TITLE
Enable request latency telemetry by default

### PR DESCRIPTION
**Pull request by ob-stripe**
r? @brandur-stripe @rattrayalex-stripe
cc @stripe/api-libraries

Cf. https://github.com/stripe/stripe-ruby/pull/800.

### CODE REVIEW

**Comment by paulasjes-stripe** [comment]
LGTM

**Comment by rattrayalex-stripe** [comment]
Can we add more detail about what sorts of telemetry are taking place?
Otherwise,

LGTM

**Comment by brandur-stripe** [comment]
> Can we add more detail about what sorts of telemetry are taking place?

IMO the call out in the README for "request latency telemetry" is probably good enough, but I guess it can't hurt to be as explicit anywhere we can.

LGTM.

**Comment by ob-stripe** [comment]
Released as 7.3.0.

**Pull request merged**
