### PR TITLE
Add bank account support

### PR DESCRIPTION
**Pull request by djeusette**
No tests added but the bank account resources are required to use the new marketplace features.

I don't expect you to merge this PR as is, but keep in mind that a full support of the bank accounts would be great in a near future.

### CODE REVIEW

**Comment by matthewarkin** [comment]
I can add some tests to this if it'll help :)

**Comment by djeusette** [comment]
Hi Matthew,

I've just added default tests based on what had been done for the customer cards.  Feel free to add new ones if needed.

**Comment by matthewarkin** [comment]
@bkrausz (just wanted to ping you on this and a couple other PRs that could use Stripe input)

**Comment by bkrausz** [comment]
Thanks for the ping! There's a small chance we'll rename this API from /bank_accounts/ to /destinations/ (to be symmetric with `sources` on customers), so let's hold off for a few more days before merging.

CC @russelldavis

**Comment by lowe0292** [comment]
Any word on this? I'm migrating from Balanced to Stripe and I'd definitely appreciate bank account support :wink:

**Comment by russelldavis** [comment]
We're indeed doing something along the lines of @bkrausz mentioned above, so unfortunately we won't be merging this as-is. We will add support for that here once it's ready though.

**Comment by matthewarkin** [comment]
Good news everyone!

So they've started adding this to some of the other libraries!

Bad news!
Instead of the endpoint being bank_accounts its external_accounts (I'm assuming this is to also supported debit cards by July).

So this will need a quick s/bank_accounts/external_accounts

**Comment by bkrausz** [comment]
Yup, if you want to update this to reference external accounts instead of bank accounts, I'm happy to merge in.

**Comment by djeusette** [comment]
Hey, thanks for the news.  I've just renamed all the references.

**Comment by bkrausz** [comment]
Thanks so much for adding this, and seeing it through to completion. CC @michelle but LGTM :)

**Comment by michelle** [comment]
Looks good. Thanks for the patch!
>
>

-- 
Sent from Gmail Mobile

**Pull request merged**
