### PR TITLE
TS Fixes: arrays of subobjects, emptyStringable fields

### PR DESCRIPTION
**Pull request by richardm-stripe**
r? @ob-stripe 
cc @jlomas-stripe @stripe/api-libraries 
1. More consistently encode "emptyStringable" types (described in the openapi spec as `anyOf(X, enum([''])`) as `X | null` instead of `X | ''`.
2. Fixes issue #766
3. A little bit of churn re: ordering of things because of codegen changes.

### CODE REVIEW

**Comment by richardm-stripe** [comment]
(List of the now-emptystringable fields instead of nullable, if useful)
  * AccountCreateParams.company.structure
  * AccountCreateParams.individual.dob
  * AccountUpdateParams.company.structure
  * AccountUpdateParams.individual.dob
  * ChargeUpdateParams.fraud_details.user_report
  * CustomerCreateParams.shipping
  * CustomerCreateParams.tax_exempt
  * CustomerCreateParams.custom_fields (also changed to array type)
  * CustomerCreateParams.invoice_settings.custom_fields (also changed to array type)
  * CustomerCreateParams.shipping.tax_exempt
  * CustomerCreateParams.tax_id_datum.shipping
  * CustomerCreateParams.tax_id_datum.tax_exempt
  * CustomerUpdateParams.shipping
  * CustomerUpdateParams.tax_exempt
  * CustomerUpdateParams.invoice_settings.custom_fields
  * InvoiceLineItemListUpcomingParams.subscription_item.billing_thresholds
  * InvoiceCreateParams.custom_fields
  * InvoiceCreateParams.transfer_data
  * InvoiceRetrieveUpcomingParams.subscription_item.billing_thresholds
  * OrderReturnOrderParams.items
  * PaymentIntentUpdateParams.setup_further_usage
  * PaymentIntentUpdateParams.shipping
  * PaymentIntentConfirmParams.setup_further_usage
  * PaymentIntentConfirmParams.shipping
  * PaymentIntentConfirmParams.mandata_data.plan
  * PersonCreateParams.dob
  * PersonUpdateParams.dob
  * ProductUpdateParams.package_dimensions
  * SkuCreateParams.inventory.value
  * SkuUpdateParams.package_dimensions
  * SkuUpdateParams.inventory.value
  * SubscriptionItemCreateParams.billing_thresholds
  * SubscriptionItemUpdateParams.billing_thresholds
  * SubscriptionScheduleCreateParams.default_settings.billing_thresholds
  * SubscriptionScheduleCreateParams.phase.billing_thresholds
  * SubscriptionScheduleCreateParams.phase.plan.billing_thresholds
  * SubscriptionScheduleUpdateParams.default_settings.billing_thresholds
  * SubscriptionScheduleUpdateParams.phase.billing_thresholds
  * SubscriptionScheduleUpdateParams.phase.plan.billing_thresholds
  * SubscriptionCreateParams.billing_thresholds
  * SubscriptionCreateParams.pending_invoice_item_interval
  * SubscriptionCreateParams.item.billing_thresholds
  * SubscriptionUpdateParams.billing_thresholds
  * SubscriptionUpdateParams.pending_invoice_item_interval
  * SubscriptionUpdateParams.transfer_data
  * SubscriptionUpdateParams.item.billing_thresholds
  * TokenCreateParams.person.dob

**Comment by ob-stripe** [comment]
> Many fields that were typed as a union with null are changed to a union with '' to better reflect the input expected by the API.

This is correct at the API level, but in many of our client libraries we prevent users from passing `''` and require them to pass `null`, which we then encode as an empty string in the request. I don't know offhand if that's the case in stripe-node, could you double-check?

**Comment by richardm-stripe** [comment]
@ob-stripe - Good point. We don't actively prevent setting an empty string in node.js, but ultimately because API Requests are urlencoded, but `null` and `''` are urlencoded identically over the wire. So we should decide solely on the basis of what type seems more natural to the user.

It seems more natural to do `| null` than `| ''` in most cases, so I've modified the codegen accordingly, but this has resulted in a new set of changes because the existing code generation did not consistently produce `| null` either (it did `| null` for `anyOf(class, enum(['']))`, but did `| ''` in cases like `anyOf(array<...>, enum(['']))` or `anyOf(primitive, enum(['']))` or `anyOf(sharedClass, enum(['']))`, if that tracks.

**Comment by richardm-stripe** [comment]
The other possibility would be defining
`type EmptyParam = null | ''` which would be backwards compatible but I think it is better to standardize on null.

**Pull request merged**
